### ISSUE TITLE
@apollo/gateway/src/executeQueryPlan.ts:248:29 - error TS2345

### ISSUE THREAD

**Issue by elbandito** [apollographql/federation#1011] opened 2021-09-09 17:18 UTC
`tsc` is failing with the following error message:
```
$ tsc
node_modules/@apollo/gateway/src/executeQueryPlan.ts:248:29 - error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'GraphQLError'.

248         context.errors.push(error);
                                ~~~~~


Found 1 error.

error Command failed with exit code 2.
```

I'm on `"@apollo/gateway": "^0.41.0",`. 

Sorry can't expose this repo to the public, but can anyone at least shed some light on how I might go about fixing this?

**Comment by trevor-scheer** [comment] 2021-09-09 17:21
Seems related to this: https://github.com/apollographql/federation/issues/1003

To be clear: it's _your_ project that won't build, not the `apollographql/federation` project that won't build, correct?

**Comment by elbandito** [comment] 2021-09-09 17:46
@trevor-scheer thanks for your reply.  I realize this may not be the most appropriate venue for this question, because I honestly can't tell if it's a bug or something to do with my project.  All I know is it was working before upgrading.  

To answer your question, you're correct.  My project is failing with that ^ error when running `yarn build`.

**Comment by trevor-scheer** [comment] 2021-09-09 17:56
@elbandito didn't mean to imply your question doesn't belong here - I think this is the best place for it! Just wanted to make I understood where the issue was happening.

Can you share your TS version and config?
Are you also upgrading your TS version during this upgrade?

Some possible quick fixes to your `tsconfig.json` which I haven't confirmed myself:
* `skipLibCheck: true`
* `useUnknownInCatchVariables: false`

I am curious to know if my changing `useUnknownInCatchVariables` to false in the gateway project is causing issues for other TS users who upgrade to that version. That would need to be fixed on our end for sure!

**Comment by trevor-scheer** [comment] 2021-09-09 18:01
In #1003, the more interesting bit is actually the change I referenced, which is a dependencies PR (+commits that I added to get CI passing)
https://github.com/apollographql/federation/pull/986
https://github.com/apollographql/federation/pull/986/commits/a5db5e8fd65892ff20d3c88083a2ffa94c93a8e1

**Comment by elbandito** [comment] 2021-09-09 18:02
@trevor-scheer you're good!  I didn't get that impression.  I'm being overly sensitive to the possibility that this could be a gray area and I'd hate to waste your time, as some who's also been on the receiving end of OSS projects.  

Let me take a look and get back to you on those details...

**Comment by elbandito** [comment] 2021-09-09 18:05
I selected/upgraded all of the following:
![Screen Shot 2021-09-09 at 12 04 44 PM](https://user-images.githubusercontent.com/1181106/132739177-776d81f4-7bbe-4271-bc3b-93f826063e74.png)

**Comment by elbandito** [comment] 2021-09-09 18:12
Also, I added `useUnknownInCatchVariables: false` and it now works, so maybe that's it 🤷🏼

**Comment by trevor-scheer** [comment] 2021-09-09 18:18
Unable to reproduce in a fresh project using these commands:
```
npm init -y
npm i @apollo/gateway graphql typescript
npx tsc --init
echo "const { ApolloGateway } = require('@apollo/gateway');" >> index.ts
npx tsc
```
I didn't need to disable that setting based on the default `tsconfig.json` created by the `tsc --init` command. Worth noting that the setting for `skipLibCheck` also doesn't trigger any errors.

Could be helpful if you shared your `tsconfig.json` or just a reproduction. I'll probably leave this issue open for a couple days and see if anyone else chimes in with a similar report.

**Comment by elbandito** [comment] 2021-09-09 18:38
Here's my `tsconfig`

```
{
  "compilerOptions": {
    /* Visit https://aka.ms/tsconfig.json to read more about this file */

    /* Basic Options */
    // "incremental": true,                   /* Enable incremental compilation */
    "target": "ES2020" /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */,
    "module": "commonjs" /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'. */,
    "lib": [
      "ES2020"
    ] /* Specify library files to be included in the compilation. */,
    "sourceMap": true,                     /* Generates corresponding '.map' file. */
    "outDir": "./dist" /* Redirect output structure to the directory. */,
    "rootDirs": ["src", "test"] /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */,

    /* Strict Type-Checking Options */
    "strict": true /* Enable all strict type-checking options. */,
    "noImplicitAny": true /* Raise error on expressions and declarations with an implied 'any' type. */,
    "noImplicitThis": true /* Raise error on 'this' expressions with an implied 'any' type. */,

    /* Additional Checks */
    "noUnusedLocals": true /* Report errors on unused locals. */,
    "noImplicitReturns": true /* Report error when not all code paths in function return a value. */,
    "noFallthroughCasesInSwitch": true /* Report errors for fallthrough cases in switch statement. */,
    "esModuleInterop": true /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */,

    /* Advanced Options */
    "skipLibCheck": true /* Skip type checking of declaration files. */,
    "forceConsistentCasingInFileNames": true, /* Disallow inconsistently-cased references to the same file. */
    "useUnknownInCatchVariables": false,
  },

  "exclude": ["node_modules", "test","**/dist/**", "**/*.test.ts", "**/*.mock.ts"],
  "include": ["src", "bin"]
}
```

**Comment by trevor-scheer** [comment] 2021-09-09 18:58
Thanks @elbandito. Interesting, using that config I still see no errors in my dummy project regardless of whether or not `useUnknownInCatchVariables` is enabled. I'm just going to close as "needs reproduction". I'll still get notifications and will reopen if a reproduction is provided. Glad we were able to get your worked around it for now, though unfortunately that setting applies to your project and may be something you'd like to have enabled in the future.

**Closed by trevor-scheer** 2021-09-09 18:58 UTC

**Comment by elbandito** [comment] 2021-09-09 19:10
@trevor-scheer  thanks for your time.  I don't know if this is separate, but when I run my app, I getting the following runtime error:
```
Error: Cannot find module '@apollo/gateway/src/datasources/types'
```

Thanks again.

**Comment by trevor-scheer** [comment] 2021-09-09 19:21
@elbandito Are you importing something `from '@apollo/gateway/src/datasources/types'`? If so, that's not something supported by the API of this package. Seems like maybe a bad auto-import.

If you're _not_ importing that anywhere in your project, I'd need to see a stack trace (and would prefer to see this in a separate issue if we continue any further please).

I find the `src` in there a bit troublesome...I think something is misconfigured or misused on your end. Runtime code should only be looking to files in the `dist` folder.

**Comment by elbandito** [comment] 2021-09-09 19:38
I am:
```
import { GraphQLDataSourceProcessOptions, GraphQLDataSourceRequestKind } from '@apollo/gateway/src/datasources/types';
```

But as you said, I can pursue this in a separate thread.

**Comment by trevor-scheer** [comment] 2021-09-09 19:46
You should be able to change that `src` to `dist` and have it work as expected. Just note, anything that isn't exported from the root, i.e. if you're not importing directly from `@apollo/gateway`, that is considered private API and not necessarily supported by us. If you find you need those types made available to you, that would make a great feature request (PR, even better!) to export them from the top level. If you choose to do that, please explain your use case (it's possible there's already a way to accomplish your goal _without_ exporting those types from the package).

**Comment by trevor-scheer** [comment] 2021-09-09 19:49
It's worth mentioning the reason that importing from `src` is problematic is because those files are all `.ts`. At runtime, `node` isn't going to load those. Everything in the `dist` directory is compiled to `.js`, which `node` should have no issue running.

**Comment by trevor-scheer** [comment] 2021-09-09 21:12
See #963
