### ISSUE TITLE
Apollo gateway: override the default fetcher with timeout/retry options not working

### ISSUE THREAD

**Issue by krishesk** [apollographql/federation#193] opened 2020-06-29 06:47 UTC
I implemented a federation gateway for my services. Since 0.16.1, developers have been able to override the default fetcher with the provided one, and this opens up a window for us to config the fetcher. According to the [documentation](https://www.apollographql.com/docs/apollo-server/api/apollo-gateway/) I should be able to pass in any options supported by [make-fetch-happen](https://www.npmjs.com/package/make-fetch-happen#extra-options). However, after some experiments, neither retry
```
fetcher: require('make-fetch-happen').defaults({
            retry: {
                retries: 1,
                minTimeout: 1000 * 20,
                maxTimeout: 1000 * 20,
            },
            onRetry() {
                console.log('### we will retry! ###')
            },
        })
```
nor timeout
```
fetcher: require('make-fetch-happen').defaults({
            timeout: 20 * 1000 // 20 seconds
            retry: 1
            onRetry() {
                console.log('### we will retry! ###')
            },
        })
``` 
worked for me. 

Am I doing anything incorrectly? 

My goal is to terminate the request after a certain amount of time so that it doesn't hang forever. I know there is an abort controller mechanism in node-fetch. Is there a way to incorporate that into the gateway?

The package name and version of Apollo showing the problem:
"@apollo/gateway": "0.16.9",
 "apollo-server": "2.9.9",
 "apollo-server-express": "2.10.0",

The expected behavior:
The request should be aborted after a certain amount of time, or a retry will be performed. 

The actual behavior:
The request just hangs there waiting for the response.

**Comment by abernix** [comment] 2020-09-30 07:23
I think using `make-fetch-happen` as a fetcher to adjust timeouts is great, and that #188 will allow the desired configuration in that regard.  Just as a point of clarity around _retries_ functionality though: generally speaking, retries are something that needs to be handled carefully.

Typically, retries do not happen automatically on `POST` requests, and `make-fetch-happen` enforces that expectation — [as noted in their documentation](https://www.npmjs.com/package/make-fetch-happen#optsretry):

> An object that can be used to tune request retry settings. Retries will only be attempted on the following conditions:
>
> - Request method is NOT `POST` AND
> - Request status is one of: 408, 420, 429, or any status in the 500-range. OR
> - Request errored with `ECONNRESET`, `ECONNREFUSED`, `EADDRINUSE`, `ETIMEDOUT`, or the fetch error request-timeout.
>
> The following are worth noting as explicitly not retried:
>
> - `getaddrinfo ENOTFOUND` and will be assumed to be either an unreachable domain or the user will be assumed offline. If a response is cached, it will be returned immediately.
> - `ECONNRESET` currently has no support for restarting. It will eventually be supported but requires a bit more juggling due to streaming.

That's to say, putting `make-fetch-happen` in as the default fetcher will result in a lot of its benefits (including proxy support, sensible defaults, timeout configurability, request pooling, transparent gzip and deflate support, and _more!_), **it will not result in gaining automatic retries support** since every GraphQL request that we send to upstream services is sent as a, per the specification above, not retried.

While it's plausible to change the dynamics of this for GraphQL, I think we should be **very cautious** when contemplating whether or not to do so.  For example, while a lot of GraphQL requests are often (read) `query`s sent as `POST` requests, a `mutation` has serious effects if retried.

If we do make `make-fetch-happen` the default fetcher, I would claim that we should very explicitly set `retry: false` on its options to make sure that if we do start sending `GET` requests (e.g., APQ?) at this layer, they won't inadvertently be retried in a potentially dangerous way prior to us ensuring the correct safe-guards are in place.

**Comment by Bhoomikapanwar** [comment] 2020-09-30 13:43
Re-quoting it from #188; 

Just to clarify, I would like to bring your attention to the following points:

The changes as done under #188 will add support for make-fetch-happen as a custom fetcher to be passed to downstream services; so this will definitely fix #191.

The default fetcher for RemoteGraphQLDataSource continues to be node-fetch. If we plan to make it as the default fetcher, I can make the required change after I get a thumbs up to go-ahead.

Moreover as far my understanding goes, #193 is bit different and is still unresolved, it points out the issue that there's a conflict between what the gateway's documentation suggests about the fetcher option and what effect does it have; quoting it from there "When specified, overrides the default Fetch API implementation which is used when communicating with downstream services."

You can see the reproduction setup here --> #193 (comment)
^^The fetcher options won't have any effect on the request that happens between the gateway and the RemoteGraphQLDataSource which is different from what the doc says.

After quite amount of debugging; it looks like the gateway never passes its fetcher to the RemoteGraphQLDataSource, that's why whatever fetcher configurations (default options) that we pass to the gateway are only utilised at the time of loading of schema from storage (schema registry) and are not passed down further to the services and instead RemoteGraphQLDataSource constructs its own fetcher and hence both are unrelated.
See here --> https://github.com/apollographql/federation/blob/main/gateway-js/src/index.ts#L572

In order to fix it and if we really plan to forward gateway's fetcher to RemoteGraphQLDataSource at the time of service initialisation. We'll need to do something like this;

return this.config.buildService
      ? this.config.buildService(serviceDef, this.fetcher)
      : new RemoteGraphQLDataSource({
          url: serviceDef.url,
          fetcher: this.fetcher
        });
And in case, we don't intend to do so, I think we should update the documentation for gateway to avoid any confusion around fetchers.

Please let me know your thoughts on it.

**Comment by abernix** [comment] 2020-09-30 17:08
I'm going to re-open this until I can review further, but I think I see what you're saying.

**Comment by mac2000** [comment] 2020-10-26 19:38
Not sure if this will work for everyone but there is workaround for now, if you are passing some headers to downstream services then you probably already using `RemoteGraphQLDataSource::willSendRequest` and from within you have access to   `request.http` which properties are spreaded while building an request, e.g.:

```js
class DataSourceWithTimeout extends RemoteGraphQLDataSource {
  willSendRequest({ request }) {
    request.http.timeout = 1000
  }
}

const gateway = new ApolloGateway({
  buildService: ({ url }) => new DataSourceWithTimeout({ url }),
});
```

**Comment by mantas-trasauskas** [comment] 2021-08-16 17:28
Hi all, had a dig through RemoteGraphQLDataSource and make-fetch-happen and spending hours on debugging I finally find this:
https://github.com/apollographql/federation/blob/44eebf9d47db76052df4f9edeeb1e42278167615/gateway-js/src/datasources/RemoteGraphQLDataSource.ts#L82

and 

https://github.com/npm/make-fetch-happen#--optsretry (Request method is NOT POST AND)

So even if you manage to pass your own fetcher using @Bhoomikapanwar  trick  it will not retry on ECONNREFUSED

**Comment by MantasTrasauskas** [comment] 2021-08-16 17:39
Hi all, had a dig through RemoteGraphQLDataSource and make-fetch-happen and spending hours on debugging I finally find this:
https://github.com/apollographql/federation/blob/44eebf9d47db76052df4f9edeeb1e42278167615/gateway-js/src/datasources/RemoteGraphQLDataSource.ts#L82

and 

https://github.com/npm/make-fetch-happen#--optsretry (Request method is NOT POST AND)

So even if you manage to pass your own fetcher using @Bhoomikapanwar  sugestion it will not retry on ECONNREFUSED

**Comment by glasser** [comment] 2021-08-17 22:02
Sounds like a fetcher other than `make-fetch-happen` would work better here, then.

**Comment by abernix** [comment] 2021-08-18 09:44
I haven't tried instrumenting it yet, but I did recently come across [`got`](https://www.npmjs.com/package/got), which seemed quite flexible.  It would need to be used in tandem with its counterpart, [`got-fetch`](https://github.com/alexghr/got-fetch) in order to be compatible with our need to be [Fetch API compliant](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API)

Again though, someone would need to explore compatibility in terms of API and TypeScript to validate!  Exploration and feedback encouraged!

**Comment by trevor-scheer** [comment] 2021-12-09 19:05
This should be resolved via https://github.com/apollographql/apollo-server/pull/4149 (a long time ago!) Sorry, digging through issues that might be related to some current work (#1284).

The mentioned change allows a custom `fetcher` to be provided directly to a `RemoteGraphQLDataSource` and should provide the flexibility this issue is requesting.

Let me know if this doesn't actually solve the issue and I'll reopen.

**Closed by trevor-scheer** 2021-12-09 19:05 UTC

**Comment by sschneider-ihre-pvs** [comment] 2023-09-04 10:18
Doesn't seem to work. Seems like the ECONNREFUSED does not reach the fetcher at all.

**Comment by sschneider-ihre-pvs** [comment] 2023-09-04 10:18
Not sure if the introspectandcompose uses the fetcher at all.

**Comment by trevor-scheer** [comment] 2023-09-05 17:31
@sschneider-ihre-pvs `IntrospectAndCompose` calls into each `RemoteGraphQLDataSource.process()` to fetch the subgraph. This allows you to specify a custom `fetcher` per subgraph (since the details of each subgraph might be different). In order to customize your `RemoteGraphQLDataSource`s, you need to specify the [`buildService`](https://www.apollographql.com/docs/apollo-server/using-federation/api/apollo-gateway/#the-buildservice-function) function in the gateway's constructor options.

**Comment by sschneider-ihre-pvs** [comment] 2023-09-06 05:32
I already did add a remotegraphqldatasource to the buildservice and added a fetcher to the datasource, but in case of no connection that fetcher does not play a role.

**Comment by sschneider-ihre-pvs** [comment] 2023-09-06 05:33
at least it does not show in the error callstack.

**Comment by vinaybedre** [comment] 2024-11-16 09:59
You can use following approach to do it.

```
import fetcher from 'make-fetch-happen';
import pRetry, { AbortError } from 'p-retry';

function fetchWithRetry(url: string, options?: FetcherRequestInit): Promise<FetcherResponse> {
  const logger = new Logger('fetchWithRetry');

  const retryableErrors = ['ECONNREFUSED', 'ECONNRESET', 'ETIMEDOUT'];

  return pRetry(
    async () => {
      try {
        return fetcher(url, options);
      } catch (error) {
        if (retryableErrors.includes(error.code)) {
          throw error;
        }

        throw new AbortError(error);
      }
    },
    {
      retries: 5,
      minTimeout: seconds(3),
      maxTimeout: seconds(30),
      maxRetryTime: minutes(1),
      onFailedAttempt: (error) => {
        logger.warn(error, `Attempt ${error.attemptNumber} failed. ${error.retriesLeft} retries left`);
      },
    },
  );
}
```

I am using `p-retry`

and finally use the function like this.

```
export class AuthenticatedDataSource extends RemoteGraphQLDataSource<Context> {
  constructor(options: ConstructorParameters<typeof RemoteGraphQLDataSource<Context>>[0]) {
    super({ ...options, fetcher: fetchWithRetry });
  }
```
