### ISSUE TITLE
Support Node v15

### ISSUE THREAD

**Issue by matthewerwin** [apollographql/federation#651] opened 2021-04-09 05:56 UTC
Presumably Node v15 is not a breaking change for this platform. Many of the associated modules in graphql, etc do not limit to v14 but the package.json file in this repo does.

I am requesting that this be modified to allow it unless there is some known incompatibility.

**Comment by abernix** [comment] 2021-04-09 10:19
Thanks for logging your request.

We don't try and support odd-numbered Node.js versions since — unlike their even-numbered siblings - they're never covered by Node.js' Long-Term-Support agreement and are often touted as not stable or unstable.  However, Node.js 16 — which will be forked from Node.js 15 and go on to be [LTS later this year (in October)](https://github.com/nodejs/release), should be out within two weeks.  We will start testing Node.js 16 it as soon as it does, and expand the tested `engines` range based on the success of those tests on that stable, destined for LTS line. 

Duplicate of https://github.com/apollographql/federation/issues/464

**Comment by abernix** [comment] 2021-04-09 10:21
Closing, but feel free to open a new issue, or a PR that makes all the changes that are necessary, when Node.js 16 comes out!  Thanks!

**Closed by abernix** 2021-04-09 10:21 UTC

**Comment by matthewerwin** [comment] 2021-04-12 06:52
@abernix this seems silly. I suppose we can fork and start releasing a version without that constraint. Essentially this means that for long periods of time -- even if there are no issues, and a user wishes to add the library in because they use Node odd-numbered versions they have to deal with engine constraints you can't even enforce later on.

So in essence, a dev can use your package in v13 (which has no LTS) but is happily included:

`  "engines": {
    "node": ">=6 <15",
    "npm": "6.x"
  }, `

But, while you have no concept of any incompatibility of v15 with the library you won't update so this doesn't break everyone who is on v15 without using `yarn install --ignore-engines` to get around it?

Day 1 that v16 comes out and you update your engine to <17 automatically everyone with v15 will suddenly be able to use this library without feeling totally annoyed that it wasn't possible since you don't try to support odd-numbered versions.

So in essence, you could just say "We don't support odd-numbered versions" and still have v15 in there. Since you "you don't support odd-numbered versions" but yet it allows v7, v9, v11, v13 right now....why not say "we don't support odd-numbered versions" and add v15 which would take 2s and remove tons of hassle in working with other libraries that have your library as a dependency which then fails to load simply because of an engines constraint that isn't even based on a "known problem"

At least go restrict all the other odd-numbered versions if you actually think there is rational to this stance on updating.

**Comment by abernix** [comment] 2021-04-12 10:39
The `engines` property expresses for posterity, within a published package's `package.json`, what versions a package is known to work with and has been tested with.  It's unsurprising that `npm`'s own [documentation demonstrates an upper-bounds to `engines`](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines).  If a future version of Node.js does break an older package which specifies an open-ended `engines` specifier, we can't go back and re-publish that package to say, "hey, it doesn't work with that version", whereas if we are defensive and express exactly what it was known to work with and tested with, we can save a user from that unfortunate mismatch and we also spare ourselves from potentially needing to chase down a bug in triaging.

Node.js 13 and all other odd-numbered releases before it are End-of-Life'd and Node.js 15 will be end-of-life'd shortly after v14 comes out in two weeks.  Nobody should be running those versions anymore and I'd claim that the depending on unstable and explicitly end-of-life'd versions of Node.js (or any software) are largely that of the user.  I suppose we could do what you're suggesting to dance around odd numbers in our `engines`, but it seems covered by this transferring of concern.  Happy to consider a PR though. 

> you have no concept of any incompatibility of v15 with the library 

We do have a concept of this: While not as volatile as the `nightly` releases of Node.js, odd-numbered versions of Node.js just aren't generally blessed as stable releases and it really doesn't seem worth opening our users up to unintentionally and often subtle bugs that can surface in unstable software.  (Fwiw, I think it's actually somewhat unfortunate that `brew` just installs odd-numbered versions of Node.js because it's precisely that which has led me to appreciate `nvm`'s notion of "stable" and I've been bitten by the latter before!).

> this seems silly. I suppose we can fork and start releasing a version without that constraint [...] add v15 which would take 2s and remove tons of hassle in working with other libraries that have your library as a dependency

Sorry you think that our more defensive approach to expressing stability and avoiding unintentional incompatibility is "silly"; just because you believe there are no issues doesn't mean there won't be any issues.  It's the responsibility of package maintainers to minimize risk and chasing any issues down is not fun / it's nice to have a stable API to point to when possibly needing to find a root-cause.

You're welcome to acknowledge the risks by passing the `--ignore-engines` flag, as you've already noted is possible and takes even less time.  That's presumably why that flag exists!  I'm happy to consider relaxing this restriction in the future, but I consider what I wrote here to be somewhat compelling.  On the other hand, it "being silly" just because it's an inconvenience to someone running experimental software isn't really motivating enough to me and this has served well for a while now nor have we been plagued by users complaining about it on either the Apollo Server or Federation repositories.

**Comment by glasser** [comment] 2021-04-13 17:06
I agree with @abernix that it makes sense to use the `engines` field to express which versions of Node we test against.

That said, we're going to be changing this very soon when v16 comes out, and I think we should strongly consider actually testing against v17 in CI once v17.0.0 is released (perhaps in a "doesn't block merges" sense) and dropping the max constraint when we have that set up.

**Comment by abernix** [comment] 2021-05-03 10:35
As of the landing of #713, we're now testing Node.js 16 and since those tests are passing, the latest versions of the `@apollo/gateway` (`0.28.0`) and `@apollo/federation` (`0.24.0`) packages have just been published with Node.js 16 in their supported `engines` range for `node`.
