### ISSUE TITLE
Strange query plan with `@shareable` root fields

### ISSUE THREAD

**Issue by lennyburdette** [apollographql/federation#2228] opened 2022-11-01 20:31 UTC
Version: Federation 2.1.2 (using rover dev) and 2.1.4 (using apollo gateway)

If two subgraphs provide the same root field that returns an interface, the query plan will try to fetch both root fields in a parallel node, and won't include the proper selection sets.

```graphql
type Query {
  search(query: String): [Product] @shareable
}

interface Product {
  title: String
}

type Book implements Product {
  title: String
  pageCount: Int
}
```

```graphql
type Query {
  search(query: String): [Product] @shareable
}

interface Product {
  title: String
}

type Movie implements Product {
  title: String
  duration: Int
}
```

For this operation:
```graphql
query Search($query: String) {
  search(query: $query) {
    ... on Book {
      title
      pageCount
    }
    ... on Movie {
      title
      duration
    }
}
```

the query plan is 
```
QueryPlan {
  Parallel {
    Fetch(service: "two") {
      {
        search(query: $query) {
          __typename
        }
      }
    },
    Fetch(service: "one") {
      {
        search(query: $query) {
          __typename
        }
      }
    },
  },
}
```

**Expected behavior**:
The query plan selects only one subgraph to resolve `Query.search` depending on cost of each choice. If the cost is equivalent, it picks the first one alphabetically by subgraph name. The selection set in the `fetch` node will include the conditional fragment only for the concrete types defined in that subgraph.

**Comment by pcmanus** [comment] 2022-11-18 14:01
So, this is actually related/similar to #1375 (the example there don't have `@shareable`, but let not that fool you: it was written on a fed2 alpha which didn't had `@shareable` yet) and the general point I made back then there apply here: I think the problem is that we shouldn't let that example compose.

To re-state why I think this shouldn't compose: I think one of the thing that is easy to misunderstand regarding `@shareable` is that it lets 2 subgraphs resolve the same field, but the strong assumption is that both subgraph *should* resolve the field "the same way". Defining precisely what "same way" means is a whole discussion, but essentially, that means same value for a value type, same entity for an entity, and that imply same runtime type in particular when union/interfaces are involved. Now, where this is a tad annoying is that we cannot really validate that `@shareable` is implemented correctly statically in generally (not that dynamically would be simple either, mind you), but the query planner planner definitively assumes that it is implemented this way, and that can lead to hard to understand results if you expected `@shareable` to work differently than it does.

All this to say that the example here kind of doesn't make sense given the `@shareable` semantic. There is no way that `search` can return the same value from each subgraph (for a fixed input), _unless_ it actually always return either `null` or an empty list, but that's obviously not the intent. And that's actually kind of why the query planner behave like it does: it actually notice that it's impossible for `search` to return some actual `Product` if it's implemented correctly and it doesn't bother.

Taking a step back, if the `@shareable` semantic is that all subgraphs must resolve the field the same way (and it is; I think it's a bit late to change it now, and besides, we'd have to define that new semantic in the first place), then it makes no sense for the subgraphs to have disjoint sets of possible runtime types for the field (as in this example), and that's actually something we can statically check, and that is the intent of #1556, a PR I wrote for #1375 a long time ago, and that was meant to be in fed 2.0, but it unfortunately slipped through the cracks. So my suggestion here would be rebase/re-assess #1556 and get that committed.

**Comment by pcmanus** [comment] 2022-11-18 14:05
> The query plan selects only one subgraph to resolve Query.search depending on cost of each choice. If the cost is equivalent, it picks the first one alphabetically by subgraph name.

Btw, this is roughly how it's meant to work on a modified example that respect the `@shareable` semantic (typically if both `Movie` and `Book` were in both subgraphs). I'll still double check it at least work correctly in that case.

**Comment by pcmanus** [comment] 2022-12-05 14:33
Closing as, as said, we'll deal with improving the experience in #1375 (and agreed offline with Lenny that this could be closed).

For the record, the explanation why the query planner gives this plan is that the query planner considers all options for a `@shareable`, including the option of resolving the field in different subgraphs for different sub-fields, as this can potentially be advantageous in a number of cases. So when the planner consider the `... on Book` fragment, it looks at both subgraph, but it realise that in the 2nd subgraph, `Book` doesn't even exists and so `search` cannot possibly return a value of that type. As such, it can just query `__typename` (to know if it returns "something" versus just resolving to `null`) and nothing else. And for that `... on Book` fragment, doing that is consider more efficient than the alternative of querying subgraph "one" (because the result fetch selection is a bit smaller essentially). Anyway, it does the same reasoning in reverse for the `... on Movie` fragments, and hence the final result.

Note that I wouldn't read too much into the exact resulting query plan: I do think the main point here is that this example is a non-working use of `@shareable`, and #1375 will hopefully soon make that clear by refusing to compose with an helpful error message.

**Closed by pcmanus** 2022-12-05 14:33 UTC
