### ISSUE TITLE
valid schema couldn't be composed. after upgrading apollo-server  3.10.2 -> 3.12.0

### ISSUE THREAD

**Issue by squarewave24** [apollographql/federation#2464] opened 2023-03-15 02:55 UTC
### Issue Description

i have a long  existing federated service which broke when i upgraded these 2 libraries 
```
-    "@apollo/gateway": "^2.1.1",
+    "@apollo/gateway": "^2.3.4",
-    "apollo-server": "^3.10.2",
+    "apollo-server": "^3.12.0",
```

```
node_modules/@apollo/gateway/src/supergraphManagers/IntrospectAndCompose/index.ts:118
      throw Error(
            ^
Error: A valid schema couldn't be composed. The following composition errors were found:
        Name "__" must not begin with "__", which is reserved by GraphQL introspection.
```

none of the services in graph add a name with `__` prefix. 

when i look at an instance running v3.10.2 i se only these names starting with __
```
__Schema
__Type
__TypeKind
__Field
__InputValue
__EnumValue
__Directive
__DirectiveLocation
```

rolling back the library versions fixes the issue. 

full trace
```
/Users/.../node_modules/@apollo/gateway/src/supergraphManagers/IntrospectAndCompose/index.ts:118
      throw Error(
            ^
Error: A valid schema couldn't be composed. The following composition errors were found:
        Name "__" must not begin with "__", which is reserved by GraphQL introspection.
    at IntrospectAndCompose.createSupergraphFromSubgraphList (/Users/.../node_modules/@apollo/gateway/src/supergraphManagers/IntrospectAndCompose/index.ts:118:13)
    at IntrospectAndCompose.updateSupergraphSdl (/Users/.../node_modules/@apollo/gateway/src/supergraphManagers/IntrospectAndCompose/index.ts:106:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async IntrospectAndCompose.initialize (/Users/.../node_modules/@apollo/gateway/src/supergraphManagers/IntrospectAndCompose/index.ts:62:30)
    at async ApolloGateway.initializeSupergraphManager (/Users/.../node_modules/@apollo/gateway/src/index.ts:390:22)
    at async ApolloGateway.load (/Users/.../node_modules/@apollo/gateway/src/index.ts:300:7)
    at async SchemaManager.start (/Users/.../node_modules/apollo-server-core/src/utils/schemaManager.ts:111:22)
    at async ApolloServer._start (/Users/.../node_modules/apollo-server-core/src/ApolloServer.ts:407:24)
    at async ApolloServer.start (/Users/.../node_modules/apollo-server-core/src/ApolloServer.ts:388:12)
```

### Link to Reproduction

private graph :(

### Reproduction Steps

dependencies
```
    "@apollo/gateway": "^2.3.4",
    "@tsconfig/node16": "^1.0.3",
    "apollo-server": "^3.12.0",
    "date-fns": "^2.29.3",
    "dotenv": "^16.0.3",
    "graphql": "^16.6.0"
```

**Comment by trevor-scheer** [comment] 2023-03-15 04:49
@squarewave24 my basic reproduction template is working with the latest versions so there's something specific to your graph that's failing validation. At the very least it would be helpful if you'd try those upgrades independently and determine if it's the gateway or server upgrade that's problematic. But without a reproduction all I can do is grasp at straws and try to get lucky reproducing your scenario.

**Comment by trevor-scheer** [comment] 2023-03-29 20:06
This is most likely related to a `graphql` version upgrade that you took, or possibly a stray change in your SDL. I can reproduce the error by adding a type like so to my SDL:
```graphql
type __ {
  oops: String
}
```

The error comes from the `graphql` library. I'm going to close this since it's most likely indirectly related to this library at best. If you can provide a reproduction that demonstrates that this library is misbehaving I'd be happy to reopen and investigate further.

**Closed by trevor-scheer** 2023-03-29 20:06 UTC
Labels: :wilted_flower: needs-reproduction
