### ISSUE TITLE
Federation 2: Type extension not found (EXTENSION_WITH_NO_BASE) on rover subgraph publish

### ISSUE THREAD

**Issue by vateseeb** [apollographql/federation#1535] opened 2022-02-23 13:48 UTC
I am new to Federation and wanted to get familiar with it with the help of the quickstart guide for federation 2. 
Following the tutorial I came to the section where I had to [register the subgraph schema](https://www.apollographql.com/docs/federation/v2/quickstart/studio-composition/). Registering the products schema via rover cli worked without issues but when I tried to register the reviews schema I got two errors:

> Encountered 2 build errors while trying to build the supergraph.
> EXTENSION_WITH_NO_BASE: [reviews] Product -> `Product` is an extension type, but `Product` is not defined in any service
> UNKNOWN: Type Query must define one or more fields.

I executed the following command that returned this error:
`rover subgraph publish MY_GRAPH_REF --routing-url https://rover.apollo.dev/quickstart/reviews/graphql --schema ./reviews.graphql --name reviews --convert`

products and reviews schemas are copied directly from the quickstart.

System information:
Windows 10
node: v16.13
@apollo/gateway: 2.0.0-alpha.6
apollo-server: 3.6.3
graphql: 15.7.0

**Comment by trevor-scheer** [comment] 2022-02-23 17:38
I don't think this is the root of your issue but it could be - the `latest2` Federation libraries expect `graphql@^16.0.0` to be installed in your project. Can you try updating and report back?

I'm also curious to know how you ended up with a non-latest version of graphql (unless you started this project awhile back). Maybe something in our docs? Only asking so we can help prevent it in the future. I suspect you're getting peer dependency warnings right now when you `npm install`?

**Comment by vateseeb** [comment] 2022-02-23 20:43
Thanks for the quick response. 
I forgot to mention that I downgraded the graphql version after reading something in another GitHub issue here that there is no graphql 16 support. Initially I had the issue with the latest graphql version. 
So unfortunately this is not the root of the issue.

**Comment by cpeacock** [comment] 2022-02-23 21:03
Hey there!  You should be able to use graphql 16 with the 2.0 versions of the gateway, I'd definitely give that another run as we shipped that a few weeks ago.

**Comment by cpeacock** [comment] 2022-02-23 21:42
My apologies, I missed the downgrade part in there.  I'll try and give it a repro.

**Comment by vateseeb** [comment] 2022-02-23 22:04
No problem. I just tried it again on my Mac. I followed the docs exactly and did everything starting with installing rover cli. Unfortunately I have the same issue again. 

MacOS 12.2
node v14.18.2
rover 0.4.3
rover-fed2 0.4.3
@apollo/gateway ^2.0.0-alpha.6
apollo-server ^3.6.3
graphql ^16.3.0

**Comment by pcmanus** [comment] 2022-02-24 08:21
The error message implies that it is coming from federation 1 composition, not federation 2. Additionally, those messages heavily suggests that composition is run only on the `reviews` subgraph, without the `products` schema.

So I highly suspect the problem is that something is set wrong in studio (and I could be wrong, but I doubt it's related to locally installed npm packages versions), since 1) it only happens when you tried composing in studio and 2) it doesn't seem to be running the proper composition version, nor does it compose both schema properly.

Now, I'm afraid I'm no expert with either rover or studio, so I'd need to dig deeper to figure more (and @cpeacock seems to already be working on trying to repro so won't stole his thunder) and just wanted to give some direction for investigation. But I'll mention one minor point I noticed scanning the ticket, and it is that in the copy-pasted command above to upload the `reviews` subgraph, the `--convert` option was provided, but it isn't in the quickstart (it's only provided for the first subgraph, the `product` one). To be clear, I have no clue if this is the problem but unless you already did, I would give a try at retrying without that flag just in case.

And as an aside, I also wanted to warn that we're in the process of finalising federation 2, but it is still a WIP and in particular the UX with for interacting fed2 with rover/studio and the documentation are "behind" (I except all this to be a lot cleaned/final within a month, if not less, but ...). So thanks a lot for giving it a shot and reporting back, we absolutely appreciate and it's very valuable to us. I simply wanted to double-check that you're not essentially beta-testing for us without knowing it (and if you'd rather not be a beta-tester, you should look at federation v1 at the moment).

**Comment by vateseeb** [comment] 2022-02-24 09:41
Thanks for your input @pcmanus. I also noticed that I accidentally used the `--convert` flag on the "reviews publish" on my first try when I was reproducing the issue on my Mac. So this time I copy-pasted exactly from the docs the CLI commands but still the same error message. 

I am aware of the beta (or even alpha?) state of fed2. But as I just wanted to get familiar with it I wanted to give fed2 a try. I didn't expect to get stuck so early with the quickstart but I totally understand that issues can occur "randomly" in this stage. 

I'm looking forward to the final version!

**Comment by cpeacock** [comment] 2022-03-15 19:17
@vateseeb apologies for the delay, this is finally rising to the top of my stack.  Should have an update this week.

**Comment by pcmanus** [comment] 2022-11-18 10:48
I'm going to close this because, as justified above, I suspect this was some alpha-state related lack of ironing out that made the wrong composition run, but fed2 has been GA for bit now and we don't have recent report of users running into such issues, so hopefully it's ironed out now. Of course, if someone continues to run on similar issues on recent versions, feel free to re-open with updated repro (or just create a new issue).

**Closed by pcmanus** 2022-11-18 10:48 UTC
