### ISSUE TITLE
Support for multiple wasm query planner objects?

### ISSUE THREAD

**Issue by dkapadia** [apollographql/federation#210] opened 2020-10-06 18:07 UTC
In our application, we instantiate multiple different Apollo Gateway objects, each with slightly different schemas. We do this because we're currently migrating code from one service to another and we want to do side-by-side testing of the old and new implementations. Having two gateway objects allows us to compare the query plans that each produces and to make a side-by-side test whenever we notice a difference between those plans.

After the wasm query planner was introduced `@apollo/gateway` in v0.20.1, we found that we could no longer do this - it seemed that we always got query plans for whichever gateway was initialized last (see reproduction code below).

I am not a rust expert, but I suspect the issue is here in [this file](https://github.com/apollographql/federation/blob/88cb9164341363d908c8a414f879ecb143017688/query-planner-wasm/src/lib.rs#L7-L23) where there currently is just a global SCHEMA and DATA objects that are always reused whenever a gateway object updates its schema. 

Given that these variables are setup right now as vectors rather than just global pointers, I'm hoping that y'all are planning to support multiple query planner objects in the future. Is that the case, or is that something you'd be open to accepting a PR for? We'd like to update to the latest query planner since it seems to fix some bugs we're experiencing, but this issue will block us from doing so.

<details>
<summary> To reproduce the issue here:</summary>

```
const { ApolloGateway } = require("@apollo/gateway");
const { parse } = require("graphql");

const gatewayA = new ApolloGateway({
  localServiceList: [
    { name: "accounts", url: "http://localhost:4001/graphql", typeDefs: parse("type Query { foo: String, bar: String}")},
    { name: "reviews", url: "http://localhost:4002/graphql", typeDefs: parse("type Query { baz: String }")},
  ],
});

const gatewayB = new ApolloGateway({
  localServiceList: [
    { name: "accounts", url: "http://localhost:4001/graphql", typeDefs: parse("type Query { foo: String }")},
    { name: "reviews", url: "http://localhost:4002/graphql", typeDefs: parse("type Query { baz: String, bar: String }")},
  ],
});

// The two schemas are different
console.log(JSON.stringify(gatewayA.schema) == JSON.stringify(gatewayB.schema)) // expected: 'false', actual: 'false'

// However the two gateway objects share a pointer to the same query
// planner wasm object, which means they will always return the same
// query plans (those of gatewayB)
console.log(gatewayA.queryPlannerPointer == gatewayB.queryPlannerPointer) // expected: 'false', actual: 'true'
```
</details>

**Comment by KoltesDigital** [comment] 2020-10-08 14:14
After upgrading dependencies I can't run my dev env anymore, in which I start multiple services and gateways in the same process. I think the problem may be the same: my system design is not compatible with a global shared schema. I'll try to run them in different processes to prevent this state sharing.

FYI here's the error:

```json
{
  "error": {
    "errors": [
      {
        "message": "unreachable",
        "extensions": {
          "code": "INTERNAL_SERVER_ERROR",
          "exception": {
            "stacktrace": [
              "RuntimeError: unreachable",
              "    at <anonymous>:wasm-function[535]:0xa3fec",
              "    at <anonymous>:wasm-function[703]:0xa94fe",
              "    at <anonymous>:wasm-function[723]:0xa9961",
              "    at <anonymous>:wasm-function[657]:0xa8692",
              "    at <anonymous>:wasm-function[264]:0x8c14b",
              "    at <anonymous>:wasm-function[28]:0x464db",
              "    at <anonymous>:wasm-function[335]:0x94b7d",
              "    at <anonymous>:wasm-function[33]:0x4ab21",
              "    at <anonymous>:wasm-function[575]:0xa5e02",
              "    at getQueryPlan (<anonymous>:wasm-function[391]:0x9a112)",
              "    at Object.module.exports.getQueryPlan (...\\node_modules\\@apollo\\query-planner-wasm\\dist\\index.js:107:24)",
              "    at Object.buildQueryPlan (...\\node_modules\\@apollo\\gateway\\dist\\buildQueryPlan.js:7:33)",
              "    at Object.ApolloGateway.executor (...\\node_modules\\@apollo\\gateway\\dist\\index.js:90:46)",
              "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
            ]
          }
        }
      }
    ]
  }
}```

There are several `unreachable!()` invocations in the source code, I can't tell which one panics. Although the root cause is the shared state, consider adding a message to each of the invocations in order to have meaningful error messages.

**Comment by Enrico2** [comment] 2020-10-13 16:41
@KoltesDigital If you're running multiple gateways in the same process, then yes, it's the same root cause. The issue brought up here is an interesting use case, and we're thinking about the right way to solve this. Stay tuned.

**Comment by Enrico2** [comment] 2020-11-02 17:43
@dkapadia Can you see if #261 solves your issue? There are instructions in the PR for how to test it.

**Comment by abernix** [comment] 2021-04-16 10:54
This should be fixed via https://github.com/apollographql/federation/pull/261#issuecomment-821091620, copy-pasted here for completeness:

> This should no longer be necessary with the landing of https://github.com/apollographql/federation/pull/622 (specifically, the changing of the query planner back to TypeScript).  Put another way, the code this changes is no longer present and the query planners are now scoped within the Gateways that generate and execute them.

**Closed by abernix** 2021-04-16 10:54 UTC
Labels: 🏓 waiting-response
