### ISSUE TITLE
Nullability error in non-nullable fields of nullable object fields

### ISSUE THREAD

**Issue by Maldron** [apollographql/federation#1205] opened 2021-11-12 18:34 UTC
When querying for the non-nullable fields of a nullable object field, an error is returned if the nullable object is null.

I'm using `"@apollo/gateway": "^2.0.0-alpha.1"` (through npm 8.1.3 with node 16.13.0).

### Intended Outcome

Given a schema like this in one subgraph
```
type Parent @key(fields: "id") {
  id: ID!
  childId: ID
  child: Child
}

extend type Child @key(fields: "id") {
  id: ID! @external
}
```

and a schema like this in another subgraph
```
type Child @key(fields: "id") {
  id: ID!
  data: Int!
}
```

When I run a query like this:
```
query Query($parentId: ID!) {
  parent(id: $parentId) {
    id
    childId
    child {
      id
      data
    }
  }
}
```

I do not expect a type error when `parent.child` resolves to null.

### Actual Outcome

I get an error like `Cannot return null for non-nullable field Child.id.` whenever `child` resolves to null.

### Reproduction

There's a repo here https://github.com/Maldron/gateway_nullability_issue with a minimum example for reproduction. In `subgraph1`, `subgraph2`, and `gateway`, run `npm install` then start the servers with `npm run build:dev`. Running the query above for `"parentId": "1"` returns without error (because `child` resolves to a non-null value), but running it with `"parentId": "2"` returns the error described above.

**Comment by Maldron** [comment] 2021-11-12 18:51
I should also note that there's an odd partial workaround by introducing an inconsistency into the supergraph:
Making the `id` optional on the `Child` stub so the schema looks like:
```
extend type Child @key(fields: "id") {
  id: ID @external
}
```

then re-running `rover fed2 supergraph compose --config ./supergraph-config.yaml > supergraph.graphql` from the `gateway` directory produces this warning:

> WARN: [InconsistentFieldType]: Field "Child.id" has mismatched, but compatible, types across subgraphs: will use type "ID" (from subgraph "subgraph1") in supergraph but "Child.id" has subtype "ID!" in subgraph "subgraph2".

Running the same query as before against the gateway does not return any errors (though it does return a `child: { id: null }` instead of just returning `child: null` as I'd expect).

**Comment by pcmanus** [comment] 2021-11-15 11:26
Thanks for very complete description and reproduction.

I believe however that the error is due to a bug in your resolvers. In particular, the error is thrown by the server of subgraph 1 and simply surfaced by the gateway, but you would get the same problem if you were to query subgraph 1 directly without federation even being in the picture.

The underlying issue is with the `child` resolver in subgraph 1, that is [this line](https://github.com/Maldron/gateway_nullability_issue/blob/main/subgraph1/src/server.ts#L55). Indeed, if `parent.childId` is `null`, which it can be, then the resolver will return the object:
```javascript
{ __typename: "Child", id: null }
```
but the graphQL execution reject this value, because while `Parent.childId` and `Parent.child` can be `null`, `Child.id` cannot. If you change the resolver to be:
```typescript
Parent: {
  child(parent: Parent) {
    return parent.childId ? { __typename: 'Child', id: parent.childId } : null;
  },
},
```
then your example will work properly.

> Running the same query as before against the gateway does not return any errors (though it does return a `child: { id: null }` instead of just returning `child: null` as I'd expect).

So modifying subgraph 1 so that `child.id` can be `null` does avoid the error since the error was due to the resolver return a child object where `id` is `null`. Note that it is correct in that case to return `child: { id: null }` since it is a valid value (this is what the warning is telling you: note how it says 'will use type "ID" (from subgraph "subgraph1") in supergraph' which means that from the point of the federated schema, `Child.id` is nullable, even if "subgraph2" happens to never return `null`) _and_ it is what the resolver returns. 

I'll close this issue as I don't think there is an underlying federation issue but please feel free to push-back if you feel I glossed over some problem/misrepresented your example.

**Closed by pcmanus** 2021-11-15 11:26 UTC

**Comment by Maldron** [comment] 2021-11-15 18:36
Ahhh, I see. I had assumed that `{ __typename: 'Child', id: parent.childId }` resolving to null would cause the `child` field to resolve to null automatically (rather than resolving to a `Child` object with null for all fields), but it makes sense that we need to explicitly return null in cases like that. Thanks so much for the detailed response!

**Comment by RebMeir** [comment] 2022-10-24 06:29
But if I have a reference to another subgraph and I have only the ID, but subgraph2 don't have this entity (it was deleted/moderated) I can't do this check:
`parent.childId ? { __typename: 'Child', id: parent.childId } : null;`
Cause the fact I have the ID, is not 100% guaranty that the entity is really exist in subgraph2 
@pcmanus
