### ISSUE TITLE
[Federation] Migrating a field to another service

### ISSUE THREAD

**Issue by KJulien2** [apollographql/federation#420] opened 2020-08-20 08:44 UTC
Hi there,

the documentation describes how to migrate a field from one service to another service (see this link: https://www.apollographql.com/docs/apollo-server/federation/entities/#migrating-a-field-to-another-service-advanced)

And - as you can read in the documentation - it says that you just have to extend the entity in your new service and add the field you want to migrate and resolve by this new service. But this causes a composition error so that the federated gateway will not start anymore: 

> This data graph is missing a valid configuration. [x-service] X.y -> Field "X.y" already exists in the schema. It cannot also be defined in this type extension. If this is meant to be an external field, add the `@external` directive.

 
But the documentation says that this error should be handled gracefully by resolving the field in whichever service is listed last in the gateways serviceList.

Am I missing/misunderstanding something here or is the documentation wrong or outdated?

Example:
```
#Service A
type User @key(fields: "id") {
    id: ID!
    name: String
    username: String
  }
```

```
#Service B which should now resolve the username
extend type User @key(fields: "id") {
    id: ID! @external
    username: String
  }
```

Thanks in advance.

Cheers

**Comment by nilligan** [comment] 2021-04-29 17:03
I'm also having this issue

**Comment by AndrewRayCode** [comment] 2021-05-05 05:31
I may have came across this same issue https://github.com/apollographql/apollo-server/issues/5175

**Comment by pcmanus** [comment] 2021-11-23 15:02
Hi. https://github.com/apollographql/federation/issues/750 is actually a dupe of this issue, but I missed that this issue was opened first and started following up there. So I'll close this issue in favour of focusing discussion on https://github.com/apollographql/federation/issues/750. Hope you won't mind.

**Closed by pcmanus** 2021-11-23 15:02 UTC
