### ISSUE TITLE
Cannot extend type "Query" because it is not defined.

### ISSUE THREAD

**Issue by mac2000** [apollographql/federation#1426] opened 2022-01-23 11:11 UTC
Can not get up and running even simple graph from given tutorials

**service.js**

```js
const { ApolloServer, gql } = require("apollo-server");
const { buildSubgraphSchema } = require('@apollo/subgraph')

const typeDefs = gql`
  type Query {
    hi: String
  }
`;

const resolvers = {
  Query: {
    hi: () => 'Hello World'
  }
};

const server = new ApolloServer({ schema: buildSubgraphSchema([{ typeDefs, resolvers }]) });

server.listen({ port: 4000 }).then(({ url }) => console.log("service:", url));
```

**gateway.js**

```js
const { ApolloGateway, IntrospectAndCompose } = require('@apollo/gateway')

const subgraphs = [
    { name: 'service', url: 'http://localhost:4000/graphql' },
]
const gateway = new ApolloGateway({
    supergraphSdl: new IntrospectAndCompose({ subgraphs }),
})

gateway
    .load()
    .then(() => console.log('success'))
    .catch(error => console.log(error.message))
```

Receiving:

```
A valid schema couldn't be composed. The following composition errors were found:
        Cannot extend type "Query" because it is not defined.
```

Versions:

```json
{
  "dependencies": {
    "@apollo/gateway": "^0.46.0",
    "@apollo/subgraph": "^0.1.5",
    "apollo-server": "^3.6.2",
    "graphql": "^16.2.0"
  }
}
```

<details>
<summary>Steps to reproduce</summary>

```bash
mkdir demo
cd demo
npm init -y -f
npm i -S @apollo/gateway @apollo/subgraph apollo-server graphql

tee service.js > /dev/null <<EOT
const { ApolloServer, gql } = require("apollo-server");
const { buildSubgraphSchema } = require('@apollo/subgraph')

const typeDefs = gql`
  type Query {
    hi: String
  }
`;

const resolvers = {
  Query: {
    hi: () => 'Hello World'
  }
};

const server = new ApolloServer({ schema: buildSubgraphSchema([{ typeDefs, resolvers }]) });

server.listen({ port: 4000 }).then(({ url }) => console.log("service:", url));
EOT

tee -a gateway.js > /dev/null <<EOT
const { ApolloGateway, IntrospectAndCompose } = require('@apollo/gateway')

const subgraphs = [
    { name: 'service', url: 'http://localhost:4000/graphql' },
]
const gateway = new ApolloGateway({
    supergraphSdl: new IntrospectAndCompose({ subgraphs }),
})

gateway
    .load()
    .then(() => console.log('success'))
    .catch(error => console.log(error.message))
EOT

node service.js &
node gateway.js
```

</details>

**Comment by glasser** [comment] 2022-01-23 16:53
Moving this over to the federation repo: @trevor-scheer, maybe an issue with the new IntrospectAndCompose?

**Comment by trevor-scheer** [comment] 2022-01-24 15:09
This is only broken by using `graphql@16`, which isn't supported by that version of the gateway. FWIW, I'm using `npm@8` and it wouldn't allow me to install that version without using the `--force` flag (it correctly chose `graphql@15.8.0`).

**Closed by trevor-scheer** 2022-01-24 15:09 UTC

**Comment by trevor-scheer** [comment] 2022-01-24 16:28
Easy mistake, no worries. Worth mentioning that v16 support on the federation 0.x branch is in progress 😄

**Comment by SidKhanna296** [comment] 2022-02-03 14:02
@trevor-scheer Is `graphql@16` incompatible with the `apollo/subgraph` services too, we have a similar error but with subgraphs ?
I had recently moved **one** of our subgraphs from `apollo/federation` - subgraph as recommended (with latest version of apollo-server) - and started my subgraph service and receiving same error (Note gateway is not running atm and is not updated with latest package versions)

- Cannot extend type "Client" because it is not defined
- Cannot extend type "Mutation" 
- Cannot extend type "Query

The way our federated schema are structured 

Client Service (Still using old federation library 0.29.0)
```
type Client {
    ....
}

extend type Quer {
     ....
}

extend type Mutation {
     ....
}
```

Member Service (The service in question updated and throwing this error)
```
extend type Client {
    ....
}

extend type Query {
    ....
}

extend type Mutation {
    ....
}
```

As you can see Client type is defined in Client service (without the updates) - and being extended in Member service
And Query and Mutation types are just plainly being extended (I don't think we have any service where type Query is not attached with the extend keyword)

keeping our subgraph `graphql@15.8` doesn't throw this error

**Comment by trevor-scheer** [comment] 2022-02-03 18:04
@SidKhanna296 up until just now, the `peerDependencies` for all federation `0.x` libraries do not include the v16 range of graphql. As such, trying to use v16 can result in unexpected behavior and it's explicitly not supported by the libraries via this version range.

You're welcome to try the latest versions which I just published - these do claim support for v16. If you run into any similar problems with our latest packages then please open an issue!
