### ISSUE TITLE
Apollo Federation with managed Schema fails with Bad Gateway when subgraph response size beyond ~300kb

### ISSUE THREAD

**Issue by repl-shenoy-sukumaran** [apollographql/federation#2819] opened 2023-10-11 08:18 UTC
### When subgraph response size is increases beyond some limit (i believe this is ~300KB) the apollo gateways query fails below error.

- Works fine if you subgraph response is small 
- Works fine when we switched to dev setup (i.e. using supergraphSdl: new IntrospectAndCompose)
- Works fine when you directly used the subgraph endpoint with large response

Note: We are managing the schema on apollo studio (Managed Schema setup)

Schema are published to apollo studio using rover with managed setup
https://www.apollographql.com/docs/federation/managed-federation/setup#4-connect-your-router-to-graphos

### Versions

```
    "@apollo/gateway": "^2.5.1",
    "@apollo/server": "^4.9.0",
    "@apollo/subgraph": "^2.5.1",
```    

### Error details
```
{
  "data": {
    "orgAnalytics": null
  },
  "errors": [
    {
      "message": "502: Bad Gateway",
      "extensions": {
        "response": {
          "url": "http://masked-url.us-west-2.elb.amazonaws.com/graphql",
          "status": 502,
          "statusText": "Bad Gateway",
          "body": "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n</body>\r\n</html>\r\n"
        },
        "code": "INTERNAL_SERVER_ERROR",
        "stacktrace": [
          "GraphQLError: 502: Bad Gateway",
          "    at BackingDataSource.errorFromResponse (/mnt/c/workspaces/time-intelligence-graph-api/node_modules/@apollo/gateway/src/datasources/RemoteGraphQLDataSource.ts:326:12)",
          "    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
          "    at BackingDataSource.sendRequest (/mnt/c/workspaces/time-intelligence-graph-api/node_modules/@apollo/gateway/src/datasources/RemoteGraphQLDataSource.ts:209:15)",
          "    at BackingDataSource.process (/mnt/c/workspaces/time-intelligence-graph-api/node_modules/@apollo/gateway/src/datasources/RemoteGraphQLDataSource.ts:164:22)",
          "    at sendOperation (/mnt/c/workspaces/time-intelligence-graph-api/node_modules/@apollo/gateway/src/executeQueryPlan.ts:559:22)",
          "    at /mnt/c/workspaces/time-intelligence-graph-api/node_modules/@apollo/gateway/src/executeQueryPlan.ts:450:41",
          "    at executeNode (/mnt/c/workspaces/time-intelligence-graph-api/node_modules/@apollo/gateway/src/executeQueryPlan.ts:372:9)",
          "    at /mnt/c/workspaces/time-intelligence-graph-api/node_modules/@apollo/gateway/src/executeQueryPlan.ts:195:27",
          "    at /mnt/c/workspaces/time-intelligence-graph-api/node_modules/@apollo/gateway/src/index.ts:827:28",
          "    at execute (/mnt/c/workspaces/time-intelligence-graph-api/node_modules/@apollo/server/src/requestPipeline.ts:540:22)"
        ]
      }
    }
  ]
}
```

### Link to Reproduction

As schemas need to publish to apollo studio with subgrpah not sure its quite possible to reproduce on codesandbox

### Reproduction Steps

- Setup apollo graphql federation Managed Schema with atleast one subgraph 
- Query the graph endpont via (Make sure your subgraph return large amount of response < 500KB)

**Comment by trevor-scheer** [comment] 2023-10-17 22:54
Without a reproduction, there isn't much I can do to help.

Suddenly getting a 502 due to subgraph size seems like you're running into an issue with AWS. Do you have logs from the subgraph service? Apollo Gateway and Apollo Server do not respond with 502s, I'm pretty sure this is an issue with your infrastructure.

I'm going to close this since I don't think it's an issue with our libs, but if you can provide a reproduction that shows it is I'm happy to reopen the issue.

**Closed by trevor-scheer** 2023-10-17 22:54 UTC
