### ISSUE TITLE
[@apollo/federation 0.21.2] types.d.ts uses GraphQLObjectType with 3 instead 2 type parameters

### ISSUE THREAD

**Issue by schulzp** [apollographql/federation#537] opened 2021-03-04 08:28 UTC
Hi! I just added `@apollo/federation 0.21.2` as a dependency in my project and get the following TS error:

```ts
node_modules/@apollo/federation/dist/types.d.ts:3:35 - error TS2707: Generic type 'GraphQLObjectType<TSource, TContext>' requires between 0 and 2 type arguments.

3 export declare const ServiceType: GraphQLObjectType<any, any, {
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4     [key: string]: any;
  ~~~~~~~~~~~~~~~~~~~~~~~
5 }>;
  ~~
```

I checked out [@apollo/federation master](https://github.com/apollographql/federation) and ran `npm run compile` with an additional compiler option `"declaration": true` in `tsconfig.build.json` an this results in a correct `dist/types.d.ts`:

```ts
import { GraphQLFieldConfig, GraphQLUnionType, GraphQLObjectType, GraphQLScalarType, GraphQLType, GraphQLNamedType, GraphQLResolveInfo } from 'graphql';
export declare const EntityType: GraphQLUnionType;
export declare const ServiceType: GraphQLObjectType<any, any>; // <-- ONLY 2 TYPE PARAMETERS
export declare const AnyType: GraphQLScalarType;
export declare type GraphQLReferenceResolver<TContext> = (reference: object, context: TContext, info: GraphQLResolveInfo) => any;
declare module 'graphql/type/definition' {
    interface GraphQLObjectType {
        resolveReference?: GraphQLReferenceResolver<any>;
    }
    interface GraphQLObjectTypeConfig<TSource, TContext> {
        resolveReference?: GraphQLReferenceResolver<TContext>;
    }
}
export declare const entitiesField: GraphQLFieldConfig<any, any>;
export declare const serviceField: GraphQLFieldConfig<any, any>;
export declare const federationTypes: GraphQLNamedType[];
export declare function isFederationType(type: GraphQLType): boolean;
//# sourceMappingURL=types.d.ts.map
```

**Other Dependencies in the Project**

```json
"typescript": "^4.2.2",
"graphql": "^15.5.0",
"apollo-server-core": "^2.21.0",
```

**Comment by glasser** [comment] 2021-03-04 20:38
It looks like the third argument was removed in https://github.com/graphql/graphql-js/pull/2488 which showed up in graphql@15.

The arguments aren't written in our source code; they are added by tsc.

So it seems like the fix will be for us to publish a version of `@apollo/federation` that is built against graphql@15 instead of graphql@14.  I'm not sure if that version will then be incompatible with graphql@14...  thoughts @trevor-scheer ?

So it sounds like this means that the current published

**Comment by schulzp** [comment] 2021-03-05 06:57
Thanks @glasser for looking digging into it. So far, I was able to patch the `types.d.ts` with [patch-package](https://www.npmjs.com/package/patch-package) and our application compiles and runs. However, we only use `@apollo/federation` for making an existing, self-contained schema available through `@apollo/gateway` and do not use features like splitting up schemas.

**Comment by glasser** [comment] 2021-03-05 18:05
OK, I'm pretty sure that if we publish with graphql@15 (ie, publishing ServiceType which passes only two args to GraphQLObjectType) we'll be OK working against graphql@14 with three args. See [https://www.typescriptlang.org/play?#code/MYGwhgzhAEDiBOYAOALAigGQPICMBWApsAC4AqAnkgQDwBQ00pAygPYCu8wB0AvNGADtyAGnqMAwiwHECAD2K9+Q0Q1IBBeAHMYfAN7QA2gGsC5AFzQIxeAEsBmgLoXB5aAF9aAPmi6xDWQD8FszsnAQA3H7Q5EESUjLykQwMAF6x6loQkR60ACZE4PDcwFJW0EwE8ABuNlwUVBYIyOjY+ERklDQuwkrknpFAA](this playground)

And in fact @martijnwalraven merged https://github.com/apollographql/federation/pull/453 a few days ago which does bump the version of graphql used when building. I've taken a look at one of the tarballs built by CI and it does contain `export declare const ServiceType: GraphQLObjectType<any, any>;` which is good.

So I think all we need to do to fix this is release from main. I'll close this since we usually close issues when their fix hits main, but I'll look into doing a release today.

**Closed by glasser** 2021-03-05 18:05 UTC

**Comment by glasser** [comment] 2021-03-05 18:58
@schulzp Can you test `@apollo/federation@0.21.3-alpha.0` and see if it works for you? I'll publish once you tell me it does. I haven't quite managed to reproduce the original failure on my machine.

**Comment by abernix** [comment] 2021-03-08 13:06
@schulzp, were you able to try this?
