### ISSUE TITLE
Fed 2 Gateway doesn't provide full selection set to requirer when `@requires` uses an `@inaccessible` object type

### ISSUE THREAD

**Issue by sachindshinde** [apollographql/federation#1866] opened 2022-05-17 20:43 UTC
**Description**
When an object type is `@inaccessible` and is used in an `@requires`, it can cause Fed 2 gateway to give the wrong selection set to the requiring subgraph (it seems to query the right data from the provider, oddly enough). Note that I'm not sure what the precise conditions are for the selection set to be missing data.

**Example**
Suppose you're running the following two subgraphs, with implementations and schemas shown below:
```typescript
import { ApolloServer, gql } from "apollo-server";
import { buildSubgraphSchema } from "@apollo/subgraph";
import { GraphQLSchemaModule } from "@apollo/subgraph/src/schema-helper/resolverMap";

const typeDefs = gql`
  extend schema
  @link(
    url: "https://specs.apollo.dev/federation/v2.0",
    import: ["@key", "@shareable"]
  )

  type Query @shareable {
    dummy: Entity
  }
  
  type Entity @key(fields: "id") {
    id: ID!
    data: Foo
  }

  interface Foo {
    foo: String!
  }
  
  interface Bar implements Foo {
    foo: String!
    bar: String!
  }
  
  type Baz implements Foo & Bar @shareable {
    foo: String!
    bar: String!
    baz: String!
  }

  type Qux implements Foo & Bar @shareable {
    foo: String!
    bar: String!
    qux: String!
  }
`;

const resolvers: GraphQLSchemaModule["resolvers"] = {
  Query: {
    dummy() {
      return {};
    },
  },
  Entity: {
    __resolveReference() {
      return {};
    },
    id() {
      return "id";
    },
    data() {
      return {
        __typename: "Baz",
        foo: "foo",
        bar: "bar",
        baz: "baz",
      };
    },
  },
};

const server = new ApolloServer({
  schema: buildSubgraphSchema({
    typeDefs,
    resolvers,
  }),
});

server.listen(4002).then(({ url }) => {
  console.log(`Subgraph Data started at ${url}`);
});

```

```typescript
import { ApolloServer, gql } from "apollo-server";
import { buildSubgraphSchema } from "@apollo/subgraph";
import { GraphQLSchemaModule } from "@apollo/subgraph/src/schema-helper/resolverMap";

const typeDefs = gql`
  extend schema
  @link(
    url: "https://specs.apollo.dev/federation/v2.0",
    import: ["@key", "@shareable", "@external", "@requires", "@inaccessible"]
  )

  type Query @shareable {
    dummy: Entity
  }

  type Entity @key(fields: "id") {
    id: ID!
    data: Foo @external
    requirer: String! @requires(fields: "data { foo ... on Bar { bar } ... on Baz { baz } ... on Qux { qux } }")
  }

  interface Foo {
    foo: String!
  }

  interface Bar implements Foo {
    foo: String!
    bar: String!
  }

  type Baz implements Foo & Bar @shareable @inaccessible {
    foo: String!
    bar: String!
    baz: String!
  }

  type Qux implements Foo & Bar @shareable {
    foo: String!
    bar: String!
    qux: String!
  }
`;

const resolvers: GraphQLSchemaModule["resolvers"] = {
  Query: {
    dummy() {
      return {};
    },
  },
  Entity: {
    __resolveReference(representation) {
      console.log(`representation: ${JSON.stringify(representation, null, 2)}`);
      return {};
    },
    id() {
      return "id";
    },
    requirer() {
      return "requirer";
    },
  },
};

const server = new ApolloServer({
  schema: buildSubgraphSchema({
    typeDefs,
    resolvers,
  }),
});

server.listen(4003).then(({ url }) => {
  console.log(`Subgraph Requirer started at ${url}`);
});

```
Running `composeServices()` from `@apollo/composition@2.0.2` yields this supergraph schema:
```graphql
schema
  @link(url: "https://specs.apollo.dev/link/v1.0")
  @link(url: "https://specs.apollo.dev/join/v0.2", for: EXECUTION)
  @link(url: "https://specs.apollo.dev/inaccessible/v0.2", for: SECURITY)
{
  query: Query
}

directive @inaccessible on FIELD_DEFINITION | OBJECT | INTERFACE | UNION | ARGUMENT_DEFINITION | SCALAR | ENUM | ENUM_VALUE | INPUT_OBJECT | INPUT_FIELD_DEFINITION

directive @join__field(graph: join__Graph!, requires: join__FieldSet, provides: join__FieldSet, type: String, external: Boolean, override: String, usedOverridden: Boolean) repeatable on FIELD_DEFINITION | INPUT_FIELD_DEFINITION

directive @join__graph(name: String!, url: String!) on ENUM_VALUE

directive @join__implements(graph: join__Graph!, interface: String!) repeatable on OBJECT | INTERFACE

directive @join__type(graph: join__Graph!, key: join__FieldSet, extension: Boolean! = false, resolvable: Boolean! = true) repeatable on OBJECT | INTERFACE | UNION | ENUM | INPUT_OBJECT | SCALAR

directive @link(url: String, as: String, for: link__Purpose, import: [link__Import]) repeatable on SCHEMA

interface Bar implements Foo
  @join__implements(graph: DATA, interface: "Foo")
  @join__implements(graph: REQUIRER, interface: "Foo")
  @join__type(graph: DATA)
  @join__type(graph: REQUIRER)
{
  foo: String!
  bar: String!
}

type Baz implements Foo & Bar
  @join__implements(graph: DATA, interface: "Foo")
  @join__implements(graph: DATA, interface: "Bar")
  @join__implements(graph: REQUIRER, interface: "Foo")
  @join__implements(graph: REQUIRER, interface: "Bar")
  @join__type(graph: DATA)
  @join__type(graph: REQUIRER)
  @inaccessible
{
  foo: String!
  bar: String!
  baz: String!
}

type Entity
  @join__type(graph: DATA, key: "id")
  @join__type(graph: REQUIRER, key: "id")
{
  id: ID!
  data: Foo @join__field(graph: DATA) @join__field(graph: REQUIRER, external: true)
  requirer: String! @join__field(graph: REQUIRER, requires: "data { foo ... on Bar { bar } ... on Baz { baz } ... on Qux { qux } }")
}

interface Foo
  @join__type(graph: DATA)
  @join__type(graph: REQUIRER)
{
  foo: String!
}

scalar join__FieldSet

enum join__Graph {
  DATA @join__graph(name: "data", url: "http://localhost:4002/")
  REQUIRER @join__graph(name: "requirer", url: "http://localhost:4003/")
}

scalar link__Import

enum link__Purpose {
  """
  `SECURITY` features provide metadata necessary to securely resolve fields.
  """
  SECURITY

  """
  `EXECUTION` features provide metadata necessary for operation execution.
  """
  EXECUTION
}

type Query
  @join__type(graph: DATA)
  @join__type(graph: REQUIRER)
{
  dummy: Entity
}

type Qux implements Foo & Bar
  @join__implements(graph: DATA, interface: "Foo")
  @join__implements(graph: DATA, interface: "Bar")
  @join__implements(graph: REQUIRER, interface: "Foo")
  @join__implements(graph: REQUIRER, interface: "Bar")
  @join__type(graph: DATA)
  @join__type(graph: REQUIRER)
{
  foo: String!
  bar: String!
  qux: String!
}
```
When we run this supergraph schema with `@apollo/gateway@2.0.2` and execute this query:
```graphql
query {
  dummy {
    requirer
  }
}
```
we see this sub-query being made to the `data` subgraph:
```graphql
query ($representations: [_Any!]!) {
  _entities(representations: $representations) {
    ... on Entity {
      data {
        __typename
        foo
        ... on Baz {
          bar
          baz
        }
        ... on Qux {
          bar
          qux
        }
      }
    }
  }
}
```
And the `data` subgraph responds with a valid response:
```json
{
  "_entities": [
    {
      "data": {
        "__typename": "Baz",
        "foo": "foo",
        "bar": "bar",
        "baz": "baz"
      }
    }
  ]
}
```

However, the representation gateway gives to the `requirer` subgraph is erroneously missing `bar`:
```
representation: {
  "__typename": "Entity",
  "data": {
    "foo": "foo",
    "baz": "baz"
  },
  "id": "id"
}
```

**Comment by pcmanus** [comment] 2022-05-20 09:24
Thanks for the thorough report. I pushed a fixed at #1873.

The issue is due to using a type condition (fragment) on an `@inaccessible` type in a `@require`, and it's a "query plan execution" issue. Meaning that the query plan generated is fine, and as noted we do correctly fetch everything required. But when the execution code "extracts" the required data to be sent to the `requirer` subgraph for the final fetch, the code needs to check if the concrete entity, a `Baz`, is a subtype of `Bar` (the inaccessible type), to know if the `bar` field should be send for that particular entity, and that check is done using the API schema, so it ends up not finding the `Bar` type at all and fallback on assuming the entity is not a `Bar` (hence why `bar` is not included in the `requirer` fetch).

Anyway, this is fixed by ensure that we use the full supergraph schema (which has inaccessible definitions) and not the API schema when we extract "required" data, since that can involve inaccessible data (and it's fine in that case since the data is for sending to subgraph; of course, for anything that is sent back to the gateway client, we continue to only use the API schema to ensure nothing inaccessible gets sent back).

I'll remark that the problem here is also a problem in fed1, but fed1 has another issue in its query plans, which is why #1867 is reproduceable _without_ `@inaccessible` (I'd comment with details on that ticket). That later issue does not affect fed2 however.

**Closed** 2022-06-29 08:13 UTC
