### ISSUE TITLE
Support for Node/nodes (Relay Global Object Identification) resolver

### ISSUE THREAD

**Issue by jukben** [apollographql/federation#1514] opened 2021-12-17 12:38 UTC
Hey! I was wondering if new router (I as understand successor of Apollo Gateway) will support Node/nodes query pattern. Why? It would eventually optimize network hops in order to support [Relay's Global Object Identification Specification](https://relay.dev/graphql/objectidentification.htm). 

See this query plan, if we would support node/nodes resolver directly in the gateway we would remove the need to have dedicated node resolver subgraph – which basically just extracts __typename from the ID.

![query-plan](https://user-images.githubusercontent.com/8135252/146545636-aa92c047-0342-4105-a2d2-3d4ceb80759d.png)

```graphql
query MyFancyQuery($ids: [ID!]!) {
  nodes(ids: $ids){
    ...on DemoUser {
      id
      name
    }
    ...on DemoFeature {
      id
    }
  }
  demoFeatures {
    edges {
      node {
        id
      }
    }
  }
}
```

# Additional Context

https://github.com/apollographql/federation/issues/1067
https://stackoverflow.com/questions/69526286/how-to-implement-relay-node-query-with-graphql-federation

**Comment by abernix** [comment] 2022-02-14 09:51
Transferred to the `federation` repository.

Duplicate of https://github.com/apollographql/federation/issues/1067

**Closed** 2022-02-14 09:51 UTC
Labels: triage
