### ISSUE TITLE
Error checking for changes to service definitions & server-health

### ISSUE THREAD

**Issue by jbpin** [apollographql/federation#754] opened 2021-05-05 08:33 UTC
Hi, we are using Apollo Studio for our federated gateway. Sometime I have issue fetching the graph with error: 
`Error checking for changes to service definitions: Cannot access Apollo storage: FetchError: request to https://storage-secrets.api.apollographql.com/... failed, reason: getaddrinfo EAI_AGAIN storage-secrets.api.apollographql.com`

It looks like this error is a DNS error but it happen often. Then from this error, my server stop working. It return a 500 error message. More importantly the health check route (.well-known/apollo/server-health) return a correct status. 
```
{
"status": "pass"
}
```

I'm expecting two behaviors:
- The server should still use its current schema
- The server-health should not return 200 pass when the server return a 500

Package version
@apollo/federation: 0.22.0
apollo-server-express: 2.21.2

**Comment by glasser** [comment] 2021-05-12 18:34
A few thoughts:

- This is a better fit for the federation repo as that is where the gateway code which fetches schemas lives now. I've transferred the issue over for you!
- Yes, this does seem like a DNS issue. Is it possible that you need to specifically allow this address to work through a firewall or something?  Are there are other names that fail in this way, or just this URL? We've heard reports of this before but haven't managed to get enough details to track it down yet.  Tracking at #463.  I haven't been able to reproduce it consistently; the research I've done on this error suggests it has a lot to do with where you run your code. Something about how Node has a fixed thread pool for talking to DNS servers or something. There may be something we can do to work around it though, maybe just retries.
- We're actually in the process of rolling out a new mechanism for fetching schemas from Apollo, which will use different names, though perhaps a DNS issue will be equally affected by the new and old mechanisms.
- Are you sure that, within a single server execution, a server that happily has a schema stops having one when this happens? That would be a big surprise.  What does match my understanding would be the symptom where a *new* server process fails to load the schema and then runs in a pretty awful state where GraphQL operations will never succeed but the health check does succeed forever. I agree with you that this is terrible behavior; fortunately, fixing how startup error handling works was the focus of AS 2.22, the next version after what you're running!  If you upgrade to at least 2.22.2 (though might as well go to 2.24 while you're at it), there's a new API you can use with `apollo-server-express`. Immediately after `server = new ApolloServer(...)`, call `await server.start()` (before you add it to your express app and start listening).  It will make sure that it can successfully load the schema (among other things) and throw otherwise (which you can handle however you like, perhaps just letting your server crash and restart).  If you use this new API you will not have the situation where your server is "running" but doesn't have a schema. (In Apollo Server 3 this API will be required rather than optional. Note that if you were using the `apollo-server` package, this functionality is built in to its `await server.listen()` API.)

I think that this addresses most of your concerns; the root cause duplicates #463 and the error handling issue is fixed if you upgrade. I'm going to close this for now.

**Closed by glasser** 2021-05-12 18:34 UTC

**Comment by jbpin** [comment] 2021-05-27 16:11
Thanks for the (long) reply. Appreciated. 
I'll make the change and wait for the server to start I let you know. (certainly on the other repo)

**Comment by andytruong** [comment] 2022-02-27 23:13
I added this to gql-gateway to deal with this kind of error:

```
  server.applyMiddleware({
    onHealthCheck: async (): Promise<any> => {
      const out = await this.server.executeOperation({
        query: `query IntrospectionQuery { __schema { queryType { name } } }`,
        operationName: 'IntrospectionQuery',
      });

      if (out.errors) {
        this.logger.error('unhealthy service', { errors: out.errors });
        throw new Error('unhealthy service');
      }

      return null;
    },
  });
```
