### ISSUE TITLE
Cannot extend type XYZ because it is not defined

### ISSUE THREAD

**Issue by MichalLytek** [apollographql/federation#1422] opened 2022-01-21 16:22 UTC
I have set up quite standard federation example project with 4 subgraphs:

Accounts service
```graphql
schema {
  query: Query
}

type User @key(fields: "id") {
  id: ID!
  username: String!
  name: String!
  birthDate: String!
}

type Query {
  me: User!
}
```

Reviews service
```graphql
schema {
  query: Query
}

type User @extends @key(fields: "id") {
  id: ID! @external
  username: String! @external
  reviews: [Review!]!
}

type Product @extends @key(fields: "upc") {
  upc: String! @external
  reviews: [Review!]!
}

type Review @key(fields: "id") {
  id: ID!
  body: String!
  author: User! @provides(fields: "username")
  product: Product!
  reviews: [Review!]!
}

type Query
```

Products service
```graphql
schema {
  query: Query
}

type Product @key(fields: "upc") {
  upc: String!
  name: String!
  price: Float!
  weight: Float!
}

type Query {
  topProducts(first: Float! = 5): [Product!]!
}
```

Inventory service
```graphql
schema {
  query: Query
}

type Product @extends @key(fields: "upc") {
  upc: String! @external
  weight: Float! @external
  price: Float! @external
  inStock: Boolean!
  shippingEstimate: Float! @requires(fields: "price weight")
}

type Query
```

However, when I load the gateway:
```ts
  const gateway = new ApolloGateway({
    supergraphSdl: new IntrospectAndCompose({
      subgraphs: [
        { name: "accounts", url: await accounts.listen(3001) },
        { name: "reviews", url: await reviews.listen(3002) },
        { name: "products", url: await products.listen(3003) },
        { name: "inventory", url: await inventory.listen(3004) },
      ],
    }),
  });

  const { schema, executor } = await gateway.load();
```

I receive weird errors:
```
Error: A valid schema couldn't be composed. The following composition errors were found:
        Cannot extend type "Query" because it is not defined. Did you mean "User"?
        Cannot extend type "User" because it is not defined.

Cannot extend type "Product" because it is not defined.
        Cannot extend type "Query" because it is not defined.
        Cannot extend type "Product" because it is not defined.
```
I use the newest  `@apollo/gateway@0.46.0` for gateway and `@apollo/subgraph@ 0.1.5` for subgraphs.

Any idea what's wrong? Same code worked for some ancient setup with `"@apollo/federation": "^0.21.2" and "@apollo/gateway": "^0.23.2"`.

**Comment by trevor-scheer** [comment] 2022-01-25 15:46
Likely related: https://github.com/apollographql/federation/issues/1426

Are you trying to use `graphql@16`? We'll have support for it soon.

Preemptively closing, but if this turns out to not be the case I'm happy to reopen and investigate. If downgrading to `graphql@15` doesn't resolve the issue, a reproduction would be helpful for me to investigate further. Thanks!

**Closed by trevor-scheer** 2022-01-25 15:46 UTC
