### ISSUE TITLE
Federation: Undefined behaviour and INTERNAL_SERVER_ERROR when returning external types that do not exist

### ISSUE THREAD

**Issue by nihalgonsalves** [apollographql/federation#376] opened 2020-03-04 12:08 UTC
If I return a Federated representation (i.e. the fields defined in `@key`) of another service, the behaviour is undefined when the other service returns null or throws an error in `__resolveReference`.

---

Reproduction Repo: https://github.com/nihalgonsalves/apollo-server-issue3859 - this includes the schema I will use as an example here. You can try out queries with different selection sets and using the IDs `should-exist`, `should-not-exist` and `should-throw`, where service B returns something, null, or throws an error respectively in its `__resolveReference` resolver.

---

- Service A defines this schema:

    ```graphql
    type Query {
      serviceAQueryReturningBType(ids: [ID!]!): [ServiceBType!]!
      serviceAQueryReturningNullableBType(ids: [ID!]!): [ServiceBType]!
    }

    extend type ServiceBType @key(fields: "id") {
      id: ID! @external
      someFieldFromB: String @external
      extendedByServiceA: String! @requires(fields: "someFieldFromB")
    }
    ```

    Note that it `@requires` a field from Service B to extend a type, but also returns this type from its own query.

- Service B defines this type:

    ```graphql
    type ServiceBType @key(fields: "id") {
      id: ID!
      someFieldFromB: String
    }
    ```

- Now, when Service B doesn't need to be called or only has to be called once, this fails gracefully:

  ```graphql
  serviceAQueryReturningBType(ids: ["should-not-exist"]) {
    id
    someFieldFromB # returns as null, after __resolveReference returns null
  }
  ```

- However, if another service (in this case, when querying `extendedByServiceA`) requires a field from Service B, the null is sent to Service A, causing an internal server error: `Field "someFieldFromB" was not found in response`:

  ```graphql
  serviceAQueryReturningBType(ids: ["should-not-exist"]) {
    id
    someFieldFromB # still returns null
    extendedByServiceA # requires someFieldFromB
  }
  ```

  ```json
  {
    "errors": [
        {
        "message": "Field \"someFieldFromB\" was not found in response.",
        "extensions": {
            "code": "INTERNAL_SERVER_ERROR",
            "exception": {
            "stacktrace": [
                "Error: Field \"someFieldFromB\" was not found in response.",
                "    at executeSelectionSet (/<redacted>/node_modules/@apollo/gateway/dist/executeQueryPlan.js:227:27)",
                "    at executeSelectionSet (/<redacted>/node_modules/@apollo/gateway/dist/executeQueryPlan.js:246:51)",
                "    at /<redacted>/node_modules/@apollo/gateway/dist/executeQueryPlan.js:133:40",
                "    at Array.forEach (<anonymous>)",
                "    at /<redacted>/node_modules/@apollo/gateway/dist/executeQueryPlan.js:132:22",
                "    at Generator.next (<anonymous>)",
                "    at /<redacted>/node_modules/@apollo/gateway/dist/executeQueryPlan.js:8:71",
                "    at new Promise (<anonymous>)",
                "    at __awaiter (/<redacted>/node_modules/@apollo/gateway/dist/executeQueryPlan.js:4:12)",
                "    at executeFetch (/<redacted>/node_modules/@apollo/gateway/dist/executeQueryPlan.js:103:12)"
            ]
            }
        }
        }
    ],
    "data": null
  }
  ```

Expected Behaviour:

- A query with a nullable return type should fail gracefully, with an error but returning data. Even if you use a nullable return type (e.g. try the queries with `serviceAQueryReturningNullableBType` in the bug reproduction repo), you still get an internal server error
- When the return type is nullable, this error shouldn't fail the entire query: if you try the nullable query with `ids: ["should-exist", "should-not-exist"]`, both objects come back as null due to the internal server error, even though one of the objects _can_ be resolved on its own.
- When non-null, a more descriptive error should be returned, and the gateway should not pass on `undefined` to the next service (the error is thrown from here: https://github.com/apollographql/apollo-server/blob/master/packages/apollo-gateway/src/executeQueryPlan.ts#L399-L406). In general it should not throw an internal server error as even non-affected queries in the request return no data when this happens.

I believe that there should also be defined behaviour/documentation about exactly what happens when `__resolveReference` throws an error or returns null.

Versions:

- `@apollo/federation` and `@apollo/gateway` version `0.13.2`
- `apollo-server` version `2.10.`

**Comment by Kartikkumargujarati** [comment] 2021-07-15 23:10
@nihalgonsalves This is the exact same issue we are facing right now. Were you able to find a stop-gap solution for this? 

@mduesterhoeft Thanks for the PR that addresses this issue. I can see that the [PR](https://github.com/orgs/apollographql/projects/9#card-45592739) was closed and is put "below the line". I am gonna be selfish here and ask if we please re-open that [PR](https://github.com/apollographql/apollo-server/pull/3914) again @trevor-scheer @abernix 😄?

**Comment by epitaphmike** [comment] 2021-08-02 13:38
I am also running into this issue. It seems strange that an entity from an external service would still try to resolve its fields if the returned is value is `null`. I am not sure if I am completely missing something @trevor-scheer @abernix 

For example: Using the example in the docs for [resolving in federation](https://www.apollographql.com/docs/federation/entities/#resolving)

**Product Service**
```graphql
type Product @key(fields: "upc") @key(fields: "sku") {
  upc: String!
  sku: String!
  price: String!
}
```

**Review Service**
```graphql
type Review {
  product: Product
}

# This is a "stub" of the Product entity (see below)
extend type Product @key(fields: "upc") {
  upc: String! @external
}
```

```graphql
{
  Review: {
    product(review) {
      return { __typename: "Product", upc: review.upc };
    }
  }
}
```

```graphql
{
  Product: {
    __resolveReference(reference) {
      return fetchProductByUPC(reference.upc);
    }
  }
}
```

```graphql
{
  reviews {
    product {
      name
      price
    }
  }
}
```

In the above query, if the product is `null` it will throw an error saying `Cannot return null for non-nullable field Product.price.`

Why would the resolving of the fields continue if the base entity `Product` was null. 

If you short circuit the returning of the reference object
```graphql
product(review) {
      return { __typename: "Product", upc: review.upc };
}
```
and instead return `null`, the resolving stops. 

```graphql
product(review) {
      return null;
}
```

If you short circuit on the `__resolveReference` with `null`, or even if it naturally returns `null` it still tries to resolve the fields of the entity.
```graphql
{
  Product: {
    __resolveReference(reference) {
      return null;
    }
  }
}
```

**Comment by pcmanus** [comment] 2021-12-14 10:28
I agree we should fix this and want to try getting a fix committed. Now, while I agree https://github.com/apollographql/apollo-server/pull/3914 is targeting the right part of the code, I do think it should be slightly modified. Anyway, as said PR couldn't be re-open per-se (since it is against the wrong repository), I took the liberty to create a new PR, https://github.com/apollographql/federation/pull/1305 (there is one for `main` too at https://github.com/apollographql/federation/pull/1306), which reuse the commit from that earlier PR but amend it with the changes I had in mind, the details on which I explain in the PR description. @mduesterhoeft: I'd particularly love to have your opinion since I essentially amended your commit.

**Closed** 2022-01-03 13:36 UTC
Labels: :pear: error-handling

**Comment by johnciprian** [comment] 2022-08-03 20:05
@epitaphmike I'm having the exact same problem as you had. Did you ever find a solution to this?

**Comment by benweatherman** [comment] 2022-08-03 20:43
howdy @johnciprian! Are you able to use `@apollo/gateway@2.0.5` or `@apollo/gateway@0.51.0`? There were changes to both major versions to address this issue (#1305 and #1306). If there are still errors with those versions, would you mind opening up a new issue with as much info as you can about how to reproduce it?

**Comment by johnciprian** [comment] 2022-08-05 19:29
@benweatherman I just tried it with v2 and it works as expected. Thank you!
